mz:
  outputs:
    chuck:
      type: materialize
      threads: 1
      host: "{{ env_var('MZ_HOST') }}"
      user: chuck@materialize.com
      password: "{{ env_var('MZ_PASSWORD') }}"
      port: 6875
      database: materialize
      schema: public
      cluster: chuck
      sslmode: require

  target: chuck