version: 2

sources:
  - name: counter_src
    database: '{{ target.database }}'
    schema: '{{ target.schema }}'
    description: counts up
    tables:
      - name: counter
        description: counts up